apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data-kafka-controller-0
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
  hostPath:
    path: "/mnt/data/kafka-0"  # Unique path for each PV

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data-kafka-controller-1
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
  hostPath:
    path: "/mnt/data/kafka-1"  # Unique path for each PV

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data-kafka-controller-2
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
  hostPath:
    path: "/mnt/data/kafka-2"  # Unique path for each PV
